### ISSUE TITLE
Compile for ElCapitain

### ISSUE THREAD

**Issue by NetForces** [bjarnoldus/mac-osx-pl2303#10]
Hi,

  Just tried compiling using Xcode 7 Beta3 under ElCapitain and I get the following:

```
clang: error: no such file or directory: '/Users/courchea/Documents/mac-osx-pl2303/Driver PL2303/Driver PL2303-Prefix.pch'
clang: error: no input files
```

**Comment by NetForces** [comment]
Ok, fixed the pch issue but now I get an error on the IOKit

**Comment by bjarnoldus** [comment]
This driver is unmaintained. The code is obsolete since 10.9. Decent tested, supported and maintained drivers are available at www.mac-usb-serial.com
